### ISSUE TITLE
Incorrect Module?

### ISSUE THREAD

**Issue by Dark4Codrutz** [OpenXbox/xbox-smartglass-nano-python#1]
https://github.com/OpenXbox/xbox-smartglass-nano-python/blob/55d9e8de0d385d8b2e53a4f7dda93a34f784d6f7/xbox/nano/scripts/client.py#L11

Trying to run the `xbox-nano-client` checks out with module not found error for `xbox.nano.render.client` (line 11 scripts.client)
It appears there is no client.py module in nano.render, the actual file in repo.
I guess a bad merge.
Shouldn't line 11 be `from xbox.nano.render.video import sdl`
It seems the old SDLClient(width, height) has been replaced by the SDLVideoRenderer class in sdl module or simply the render.client is missing?

**Comment by tuxuser** [comment]
Fixed with 016ae99b9f861360828ebdc31dbac20961c2e977, `xbox.nano.render.client` was missing from *packages* section in setup.py

Thanks for the report!
