### ISSUE TITLE
master is out of sync with pip package

### ISSUE THREAD

**Issue by elbowdonkey** [OpenXbox/xbox-smartglass-nano-python#14]
I'm not too familiar with `pip`, but it appears as if the code in `master` is newer than what `pip` installs. Most importantly, the changes that allow for controller input seem to be missing from `0.9.4`.

**Comment by tuxuser** [comment]
Once PR #15 is accepted a new version will be uploaded.

**Comment by tuxuser** [comment]
Tracked in #18
