### ISSUE TITLE
Library is currently broken

### ISSUE THREAD

**Issue by tuxuser** [OpenXbox/xbox-smartglass-nano-python#18]
This library is currently broken.
Update to accommodate latest xbox-smartglass-core  is pending.

**Comment by mpearon** [comment]
Just checking on the status of this issue.  Your work is appreciated.

**Comment by tuxuser** [comment]
Try `v0.10.0`

**Comment by mpearon** [comment]
@tuxuser - That appears to have installed correctly!  I'll get to playing around and report back.  Again, thank you for your work!

**Comment by mpearon** [comment]
@tuxuser - I was able to use the poweron, poweroff and nano-client functionality without issue! Great job!
