### ISSUE TITLE
XBox Series S/X Support

### ISSUE THREAD

**Issue by SolidTux** [OpenXbox/xbox-smartglass-nano-python#21]
What is currently missing for supporting the new protocol version and therefore the new XBoxes? Is there a specific part where I could help with?

**Comment by tuxuser** [comment]
Implementation of Nano v3 is missing entirely. Is that something you want to help with?

**Comment by SolidTux** [comment]
Yes, but I have no idea where to start.

**Comment by 404oops** [comment]
The Xbox One X is very similar to the Series X|S, therefore if you have an Xbox One/X/S then you should be capable of running those games

**Comment by wangkuan** [comment]
I have an Xbox series X, which only has remote game function in the latest system.

Remote games can make the client directly connect to the game controller through the Internet

In addition, the network of the controller can be in NAT, and there is no need to disclose the accessible ports.

At least it looks like it's penetrated through the intranet

**Comment by wangkuan** [comment]
I guess Microsoft provides a server to support FRP

But I'm in China, China's Xbox network is terrible

But the function of remote game can provide me with high-speed game experience

It's really amazing

**Comment by wangkuan** [comment]
I just got to know UPnP, please forgive my stupidity.

So it looks like Xbox app is directly connected to the controller.

Maybe xbox live has the ability of service discovery?

**Comment by tuxuser** [comment]
So there is a gamecontroller that directly connects to the cloud and TV wirelessly to let you gamestream? wow.
If thats not what you are saying, I dont understand your posts at all.

**Comment by 404oops** [comment]
Maybe it's a Plug-n'-play android device, i'm not entirely sure...

**Comment by tinogoehlert** [comment]
Hi, my Xbox Series X arrives tomorrow and i would like to support you with the Implementation of Nano v3. Do you have any information about the protocol yet? or do we have to reverse engineer it? Did you already run some tests to verify if the crypto / salting part is still the same?

**Comment by 404oops** [comment]
> Hi, my Xbox Series X arrives tomorrow and i would like to support you with the Implementation of Nano v3. Do you have any information about the protocol yet? or do we have to reverse engineer it? Did you already run some tests to verify if the crypto / salting part is still the same?

As the devs said before, nano v3 is not openly available to the public, so they can't implement series x|s support. When it does eventually, it will be supported, but until then, you'd have to stick to your phone.

**Comment by BobbyShoe** [comment]
Just checking to see if there has been any updates on nano v3 for XBox Series X.  If you have any additional information I could possibly try to help with implementation or testing of the feature.

**Comment by tuxuser** [comment]
https://github.com/unknownskl/xbox-xcloud-client
