### ISSUE TITLE
Could not install

### ISSUE THREAD

**Issue by mawi675lr81** [OpenXbox/xbox-smartglass-nano-python#31]
Installing collected packages: av, xbox-smartglass-nano
  Attempting uninstall: av
    Found existing installation: av 8.0.3
    Uninstalling av-8.0.3:
      Successfully uninstalled av-8.0.3
    Running setup.py install for av ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j58v4ci6/av_0f060234e787425783bd7125801677e6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j58v4ci6/av_0f060234e787425783bd7125801677e6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ifet1fzt/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/shiv/.local/include/python3.9/av
         cwd: /tmp/pip-install-j58v4ci6/av_0f060234e787425783bd7125801677e6/
    Complete output (48 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/av
    copying av/deprecation.py -> build/lib.linux-x86_64-3.9/av
    copying av/datasets.py -> build/lib.linux-x86_64-3.9/av
    copying av/__main__.py -> build/lib.linux-x86_64-3.9/av
    copying av/__init__.py -> build/lib.linux-x86_64-3.9/av
    creating build/lib.linux-x86_64-3.9/av/video
    copying av/video/__init__.py -> build/lib.linux-x86_64-3.9/av/video
    creating build/lib.linux-x86_64-3.9/av/subtitles
    copying av/subtitles/__init__.py -> build/lib.linux-x86_64-3.9/av/subtitles
    creating build/lib.linux-x86_64-3.9/av/sidedata
    copying av/sidedata/__init__.py -> build/lib.linux-x86_64-3.9/av/sidedata
    creating build/lib.linux-x86_64-3.9/av/filter
    copying av/filter/__init__.py -> build/lib.linux-x86_64-3.9/av/filter
    creating build/lib.linux-x86_64-3.9/av/data
    copying av/data/__init__.py -> build/lib.linux-x86_64-3.9/av/data
    creating build/lib.linux-x86_64-3.9/av/container
    copying av/container/__init__.py -> build/lib.linux-x86_64-3.9/av/container
    creating build/lib.linux-x86_64-3.9/av/codec
    copying av/codec/__init__.py -> build/lib.linux-x86_64-3.9/av/codec
    creating build/lib.linux-x86_64-3.9/av/audio
    copying av/audio/__init__.py -> build/lib.linux-x86_64-3.9/av/audio
    running build_ext
    running config
    PyAV: 8.0.2 (unknown commit)
    Python: 3.9.6 (default, Jun 29 2021, 00:00:00) \n[GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
    platform: Linux-5.12.14-300.fc34.x86_64-x86_64-with-glibc2.33
    extension_extra:
    	include_dirs: [b'include']
    	libraries: []
    	library_dirs: []
    	define_macros: []
    	runtime_library_dirs: []
    config_macros:
    	PYAV_COMMIT_STR="unknown-commit"
    	PYAV_VERSION=8.0.2
    	PYAV_VERSION_STR="8.0.2"
    Could not find libavformat with pkg-config.
    Could not find libavcodec with pkg-config.
    Could not find libavdevice with pkg-config.
    Could not find libavutil with pkg-config.
    Could not find libavfilter with pkg-config.
    Could not find libswscale with pkg-config.
    Could not find libswresample with pkg-config.
    ----------------------------------------
  Rolling back uninstall of av
  Moving to /home/shiv/.local/bin/pyav
   from /tmp/pip-uninstall-974xbu_u/pyav
  Moving to /home/shiv/.local/lib/python3.9/site-packages/av-8.0.3.dist-info/
   from /home/shiv/.local/lib/python3.9/site-packages/~v-8.0.3.dist-info
  Moving to /home/shiv/.local/lib/python3.9/site-packages/av.libs/
   from /home/shiv/.local/lib/python3.9/site-packages/~v.libs
  Moving to /home/shiv/.local/lib/python3.9/site-packages/av/
   from /home/shiv/.local/lib/python3.9/site-packages/~v
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j58v4ci6/av_0f060234e787425783bd7125801677e6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j58v4ci6/av_0f060234e787425783bd7125801677e6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ifet1fzt/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/shiv/.local/include/python3.9/av Check the logs for full command output.

**Comment by Meganium97** [comment]
Run `pip install av` and tell me what the output error is.

**Comment by mawi675lr81** [comment]
> Run pip install av and tell me what the output error is.

pip install av
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: av in ./.local/lib/python3.9/site-packages (8.0.3)

Same output when pip3 is used

**Comment by mawi675lr81** [comment]
ran the av command with sudo. Output:

WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting av
  Downloading av-8.0.3-cp39-cp39-manylinux2010_x86_64.whl (37.7 MB)
     |████████████████████████████████| 37.7 MB 24.6 MB/s 
Installing collected packages: av
Successfully installed av-8.0.3

Then ran the install command without and with sudo. same error as in the original post

**Comment by Meganium97** [comment]
you're installing from source, correct?

**Comment by mawi675lr81** [comment]
> you're installing from source, correct?

I’m sorry, I don’t understand

**Comment by Meganium97** [comment]
If you don't understand then you probably aren't

**Comment by Meganium97** [comment]
Okay. Try downloading the repository directly and installing it using setup.py with the command `python3 setup.py`.

**Comment by mawi675lr81** [comment]
> Okay. Try downloading the repository directly and installing it using setup.py with the command `python3 setup.py`.

That worked. Had to do `sudo python3 setup.py install` though

**Comment by Meganium97** [comment]
I would like to meantion that this error has been fixed in the latest update.
