### ISSUE TITLE
Copy controller_db.txt to bdist

### ISSUE THREAD

**Issue by tuxuser** [OpenXbox/xbox-smartglass-nano-python#4]
Currently controller_db.txt is not copied to the bdist / pypi deployed package.

path: `xbox/nano/render/input/controller_db.txt`

- Add path to include in `Manifest.in`
- Add `include_package_data=True` to `setup. py`

**Comment by Nirajn2311** [comment]
Working on it.

**Comment by uzerjamal** [comment]
Implemented this feature in #6

**Comment by tuxuser** [comment]
Thanks!
